Q1: Pandas version

In [1]:
import pandas as pd

pd.__version__

'3.0.6'

Q2: Records Count

In [2]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

In [3]:
df.shape

(10000, 11)

Q3: Fuel Types

In [4]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [8]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Q4: missing values

In [11]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5: Maximum fuel efficiency for asian cars

In [12]:
asia = df[df['origin'] == 'Asia']

In [15]:
asia['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6: Horsepower median before/after filling missing values

In [18]:
median_before = df['horsepower'].median
median_before

<bound method Series.median of 0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64>

In [25]:
most_frequent = df['horsepower'].mode()[0]
most_frequent

np.float64(252.0)

In [21]:
df_q6 = df.copy()

In [22]:
df_q6['horsepower'] = df_q6['horsepower'].fillna(most_frequent)

In [24]:
median_after = df_q6['horsepower'].median()
median_after

np.float64(252.0)

Q7: Linear Algebra

In [26]:
asia = df[df['origin'] == 'Asia']

In [27]:
asia[['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [28]:
asia[['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [41]:
import numpy as np

In [42]:
X = np.array(asia[['vehicle_weight', 'model_year']].head(7).values)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [31]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [34]:
XTX_inv = np.linalg.inv(XTX)

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w=(XTX)−1XTy

In [43]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [44]:
w.sum()

np.float64(0.36919696904925486)