In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

df = pd.read_csv(data)

In [3]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [4]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [5]:
categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

In [6]:
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [7]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

pd.to_numeric(df.totalcharges)

In [8]:
df['totalcharges'] = pd.to_numeric(
    df['totalcharges'],
    errors='coerce'
)

In [9]:
df.totalcharges.isnull().sum()

np.int64(11)

In [10]:
df['totalcharges'] = df['totalcharges'].fillna(0)

In [11]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [12]:
df.churn = (df.churn == 'yes').astype(int)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
df_full_train , df_test = train_test_split(df, test_size=0.2, random_state=1)

In [15]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [16]:
len(df_train), len(df_val), len(df_test), len(df_full_train), len(df)

(4225, 1409, 1409, 5634, 7043)

In [17]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [18]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [19]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [20]:
df_full_train.head().T

,1814,5946,3881,2389,3676
customerid,5442-pptjy,6261-rcvns,2176-osjuv,6161-erdgd,2364-ufrom
gender,male,female,male,male,male
seniorcitizen,0,0,0,0,0
partner,yes,no,yes,yes,no
dependents,yes,no,no,yes,no
tenure,12,42,71,71,30
phoneservice,yes,yes,yes,yes,yes
multiplelines,no,no,yes,yes,no
internetservice,no,dsl,dsl,dsl,dsl
onlinesecurity,no_internet_service,yes,yes,yes,yes
onlinebackup,no_internet_service,yes,yes,no,yes
deviceprotection,no_internet_service,yes,no,yes,no
techsupport,no_internet_service,yes,yes,yes,yes
streamingtv,no_internet_service,no,no,yes,yes
streamingmovies,no_internet_service,yes,no,yes,no
contract,two_year,one_year,two_year,one_year,one_year
paperlessbilling,no,no,no,no,no
paymentmethod,mailed_check,credit_card_(automatic),bank_transfer_(automatic),electronic_check,electronic_check
monthlycharges,19.7,73.9,65.15,85.45,70.4
totalcharges,258.35,3160.55,4681.75,6300.85,2044.75
churn,0,1,0,0,0

In [21]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [22]:
df_full_train.churn.value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

In [23]:
df_full_train.churn.value_counts(normalize=True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [24]:
global_churn_rate = df_full_train.churn.mean()
global_churn_rate

np.float64(0.26996805111821087)

df.churn.mean()

In [25]:
numerical = [
    'tenure',
    'monthlycharges',
    'totalcharges'
]

In [26]:
categorical = [
    'gender',
    'seniorcitizen',
    'partner',
    'dependents',
    'phoneservice',
    'multiplelines',
    'internetservice',
    'onlinesecurity',
    'onlinebackup',
    'deviceprotection',
    'techsupport',
    'streamingtv',
    'streamingmovies',
    'contract',
    'paperlessbilling',
    'paymentmethod'
]

In [27]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [28]:
churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()

In [29]:
churn_female - global_churn_rate

np.float64(0.006855983216553063)

In [30]:
churn_female / global_churn_rate

np.float64(1.0253955354648652)

In [31]:
df_group = df_full_train.groupby(
    'gender'
).churn.agg(['mean', 'count'])
df_group

            mean  count
gender
female  0.276824   2796
male    0.263214   2838

In [32]:
df_group['diff'] = (
    df_group['mean'] - global_churn_rate
)
df_group['risk'] = (
    df_group['mean'] / global_churn_rate
)
df_group

            mean  count      diff      risk
gender
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

In [33]:
from IPython.display import display

In [34]:
for c in categorical:

    print(c)

    df_group = df_full_train.groupby(c).churn.agg([
        'mean',
        'count'
    ])

    df_group['diff'] = (
        df_group['mean'] -
        global_churn_rate
    )

    df_group['risk'] = (
        df_group['mean'] /
        global_churn_rate
    )

    display(df_group)

    print()

gender

            mean  count      diff      risk
gender
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

seniorcitizen

                   mean  count      diff      risk
seniorcitizen
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208

partner

             mean  count      diff      risk
partner
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

dependents

                mean  count      diff      risk
dependents
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

phoneservice

                  mean  count      diff      risk
phoneservice
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412

multiplelines

                      mean  count      diff      risk
multiplelines
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

internetservice

                     mean  count      diff      risk
internetservice
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201

onlinesecurity

                         mean  count      diff      risk
onlinesecurity
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

onlinebackup

                         mean  count      diff      risk
onlinebackup
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

deviceprotection

                         mean  count      diff      risk
deviceprotection
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

techsupport

                         mean  count      diff      risk
techsupport
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

streamingtv

                         mean  count      diff      risk
streamingtv
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

streamingmovies

                         mean  count      diff      risk
streamingmovies
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

contract

                    mean  count      diff      risk
contract
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

paperlessbilling

                      mean  count      diff      risk
paperlessbilling
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560

paymentmethod

                               mean  count      diff      risk
paymentmethod
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

In [35]:
from sklearn.metrics import mutual_info_score

In [36]:
mutual_info_score(
    df_full_train.churn,
    df_full_train.contract
)

0.0983203874041556

In [37]:
def mutual_info_churn_score(series):
    return mutual_info_score(
        series,
        df_full_train.churn
    )

In [38]:
mi = df_full_train[categorical].apply(
    mutual_info_churn_score
)

mi.sort_values(ascending=False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

In [39]:
df_full_train[numerical].corrwith(
    df_full_train.churn
)

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

In [40]:
from sklearn.feature_extraction import DictVectorizer

In [41]:
train_dicts = df_train[
    categorical + numerical
].to_dict(orient='records')

In [42]:
dv = DictVectorizer(sparse=False)

In [43]:
X_train = dv.fit_transform(train_dicts)

In [44]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',
       'streamingmovies=yes', 'streamingtv=no',
       'streamingtv=no_internet_service', 'streamingtv=yes',
       'techsupport=no', 'techsupport=no_internet_service',
       'techsupport=yes', 'tenure', 'totalcharges'], dtype=object)

In [45]:
val_dicts = df_val[
    categorical + numerical
].to_dict(orient='records')

X_val = dv.transform(val_dicts)

In [46]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
model = LogisticRegression()

In [49]:
model.fit(X_train, y_train)

C:\Users\ashis\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [50]:
model.intercept_[0]

np.float64(-0.10910575411731115)

In [51]:
model.coef_[0]

array([ 4.75717837e-01, -1.74974117e-01, -4.08489634e-01, -2.99885245e-02,
       -7.77573894e-02,  6.26589495e-02, -8.90715400e-02, -8.13333235e-02,
       -3.43043508e-02, -7.34415631e-02, -3.35503209e-01,  3.16828835e-01,
       -8.90715400e-02,  3.68850280e-03, -2.58257758e-01,  1.41848117e-01,
        8.66372707e-03,  6.25260874e-02, -8.90715400e-02, -8.12004613e-02,
        2.65657105e-01, -8.90715400e-02, -2.84331479e-01, -2.31072067e-01,
        1.23326153e-01, -1.66360757e-01,  5.86148436e-02, -8.70789120e-02,
       -3.19911720e-02,  7.00844586e-02, -5.87602885e-02,  1.41848117e-01,
       -2.49594031e-01,  2.15655184e-01, -1.20527699e-01, -8.90715400e-02,
        1.01853325e-01, -7.09790548e-02, -8.90715400e-02,  5.23046809e-02,
        2.13260458e-01, -8.90715400e-02, -2.31934832e-01, -7.04966672e-02,
        3.83087375e-04])

In [52]:
model.predict_proba(X_val)

array([[0.99103201, 0.00896799],
       [0.79545784, 0.20454216],
       [0.78784822, 0.21215178],
       ...,
       [0.8636778 , 0.1363222 ],
       [0.20004633, 0.79995367],
       [0.16241793, 0.83758207]], shape=(1409, 2))

In [53]:
y_pred = model.predict_proba(X_val)[:, 1]

In [54]:
churn_decision = y_pred >= 0.5

In [55]:
(y_val == churn_decision).mean()

np.float64(0.8026969481902059)

In [56]:
feature_names = dv.get_feature_names_out()

In [57]:
weights = model.coef_[0]

In [58]:
dict(zip(feature_names, weights))

{'contract=month-to-month': np.float64(0.4757178372842867),
 'contract=one_year': np.float64(-0.17497411734270535),
 'contract=two_year': np.float64(-0.40848963385997433),
 'dependents=no': np.float64(-0.029988524469422698),
 'dependents=yes': np.float64(-0.07775738944919715),
 'deviceprotection=no': np.float64(0.06265894954160413),
 'deviceprotection=no_internet_service': np.float64(-0.08907153997018441),
 'deviceprotection=yes': np.float64(-0.08133332349162709),
 'gender=female': np.float64(-0.03430435084481633),
 'gender=male': np.float64(-0.07344156307741925),
 'internetservice=dsl': np.float64(-0.335503209150072),
 'internetservice=fiber_optic': np.float64(0.316828835203685),
 'internetservice=no': np.float64(-0.08907153997018441),
 'monthlycharges': np.float64(0.0036885028032743704),
 'multiplelines=no': np.float64(-0.25825775848110133),
 'multiplelines=no_phone_service': np.float64(0.14184811748704532),
 'multiplelines=yes': np.float64(0.008663727070108566),
 'onlinebackup=no': np.float64(0.0625260873595781),
 'onlinebackup=no_internet_service': np.float64(-0.08907153997018441),
 'onlinebackup=yes': np.float64(-0.08120046131082277),
 'onlinesecurity=no': np.float64(0.26565710479120636),
 'onlinesecurity=no_internet_service': np.float64(-0.08907153997018441),
 'onlinesecurity=yes': np.float64(-0.28433147874461856),
 'paperlessbilling=no': np.float64(-0.2310720673804238),
 'paperlessbilling=yes': np.float64(0.12332615345942319),
 'partner=no': np.float64(-0.16636075748481408),
 'partner=yes': np.float64(0.058614843563710904),
 'paymentmethod=bank_transfer_(automatic)': np.float64(-0.08707891196938318),
 'paymentmethod=credit_card_(automatic)': np.float64(-0.03199117199514225),
 'paymentmethod=electronic_check': np.float64(0.07008445858115271),
 'paymentmethod=mailed_check': np.float64(-0.05876028853506057),
 'phoneservice=no': np.float64(0.14184811748704532),
 'phoneservice=yes': np.float64(-0.24959403140914724),
 'seniorcitizen': np.float64(0.2156551841782109),
 'streamingmovies=no': np.float64(-0.1205276986285192),
 'streamingmovies=no_internet_service': np.float64(-0.08907153997018441),
 'streamingmovies=yes': np.float64(0.10185332467615617),
 'streamingtv=no': np.float64(-0.07097905480962939),
 'streamingtv=no_internet_service': np.float64(-0.08907153997018441),
 'streamingtv=yes': np.float64(0.052304680858474666),
 'techsupport=no': np.float64(0.21326045820711215),
 'techsupport=no_internet_service': np.float64(-0.08907153997018441),
 'techsupport=yes': np.float64(-0.2319348321480814),
 'tenure': np.float64(-0.070496667162354),
 'totalcharges': np.float64(0.0003830873753095151)}

In [59]:
for feature, weight in zip(
    feature_names,
    weights
):
    print(feature, weight)

contract=month-to-month 0.4757178372842867
contract=one_year -0.17497411734270535
contract=two_year -0.40848963385997433
dependents=no -0.029988524469422698
dependents=yes -0.07775738944919715
deviceprotection=no 0.06265894954160413
deviceprotection=no_internet_service -0.08907153997018441
deviceprotection=yes -0.08133332349162709
gender=female -0.03430435084481633
gender=male -0.07344156307741925
internetservice=dsl -0.335503209150072
internetservice=fiber_optic 0.316828835203685
internetservice=no -0.08907153997018441
monthlycharges 0.0036885028032743704
multiplelines=no -0.25825775848110133
multiplelines=no_phone_service 0.14184811748704532
multiplelines=yes 0.008663727070108566
onlinebackup=no 0.0625260873595781
onlinebackup=no_internet_service -0.08907153997018441
onlinebackup=yes -0.08120046131082277
onlinesecurity=no 0.26565710479120636
onlinesecurity=no_internet_service -0.08907153997018441
onlinesecurity=yes -0.28433147874461856
paperlessbilling=no -0.2310720673804238
paperlessbilling=yes 0.12332615345942319
partner=no -0.16636075748481408
partner=yes 0.058614843563710904
paymentmethod=bank_transfer_(automatic) -0.08707891196938318
paymentmethod=credit_card_(automatic) -0.03199117199514225
paymentmethod=electronic_check 0.07008445858115271
paymentmethod=mailed_check -0.05876028853506057
phoneservice=no 0.14184811748704532
phoneservice=yes -0.24959403140914724
seniorcitizen 0.2156551841782109
streamingmovies=no -0.1205276986285192
streamingmovies=no_internet_service -0.08907153997018441
streamingmovies=yes 0.10185332467615617
streamingtv=no -0.07097905480962939
streamingtv=no_internet_service -0.08907153997018441
streamingtv=yes 0.052304680858474666
techsupport=no 0.21326045820711215
techsupport=no_internet_service -0.08907153997018441
techsupport=yes -0.2319348321480814
tenure -0.070496667162354
totalcharges 0.0003830873753095151

In [60]:
model.intercept_[0]

np.float64(-0.10910575411731115)

In [61]:
small = [
    'contract',
    'tenure',
    'monthlycharges'
]

In [62]:
dicts_train_small = df_train[
    small
].to_dict(orient='records')

In [63]:
dv_small = DictVectorizer(sparse=False)

X_train_small = dv_small.fit_transform(
    dicts_train_small
)

In [64]:
model_small = LogisticRegression()

model_small.fit(
    X_train_small,
    y_train
)

LogisticRegression()

In [65]:
dv_small.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'monthlycharges', 'tenure'], dtype=object)

In [66]:
model_small.coef_[0]

array([ 0.9711394 , -0.02379507, -0.94828863,  0.02748534, -0.03619005])

In [67]:
y_full_train = df_full_train.churn.values

In [68]:
del df_full_train['churn']

In [69]:
dicts_full_train = df_full_train[
    categorical + numerical
].to_dict(orient='records')

In [70]:
dv = DictVectorizer(sparse=False)

In [71]:
X_full_train = dv.fit_transform(
    dicts_full_train
)

In [72]:
model = LogisticRegression()

model.fit(
    X_full_train,
    y_full_train
)

C:\Users\ashis\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [73]:
dicts_test = df_test[
    categorical + numerical
].to_dict(orient='records')

In [74]:
X_test = dv.transform(dicts_test)

In [75]:
y_pred = model.predict_proba(
    X_test
)[:, 1]

In [76]:
churn_decision = y_pred >= 0.5

In [77]:
(y_test == churn_decision).mean()

np.float64(0.8140525195173882)

In [78]:
customer = {
    'gender': 'female',
    'seniorcitizen': 0,
    'partner': 'yes',
    'dependents': 'no',
    'phoneservice': 'yes',
    'multiplelines': 'no',
    'internetservice': 'fiber_optic',
    'onlinesecurity': 'no',
    'onlinebackup': 'yes',
    'deviceprotection': 'no',
    'techsupport': 'no',
    'streamingtv': 'yes',
    'streamingmovies': 'yes',
    'contract': 'month-to-month',
    'paperlessbilling': 'yes',
    'paymentmethod': 'electronic_check',
    'tenure': 3,
    'monthlycharges': 95,
    'totalcharges': 285
}

In [79]:
X_customer = dv.transform([customer])

In [80]:
model.predict_proba(X_customer)

array([[0.22906189, 0.77093811]])

In [81]:
churn_probability = model.predict_proba(
    X_customer
)[0, 1]

In [82]:
churn_probability >= 0.5

np.True_

In [83]:
dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]

churn = y_pred >= 0.5

C:\Users\ashis\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(